; To use xmlSigner for signing your XML files, you need the following:
;
; 1. A code-signing certificate installed in the Windows certificate store.
; 2. The "xmlSigner.exe" binary - it's a free software & open source project. You can find the source code here:
;    https://github.com/donho/xmlSigner
;    compile it & sign it with your trusted certificate to prevent the block comes from Smart App Control.
; 3. A configuration file named "xmlSigner.ini" (this file). Place it next to "xmlSigner.exe" and adjust the parameters according your needs.


; The certificate thumbprint is required to locate the certificate in the Windows certificate store.
; Can be found by opening the certificate details tab and copying the 'Thumbprint' value.
[thumbprint]
YOUR_CERTIFICATE_THUMBPRINT

; The XML files to sign, using their full paths.
[filesToSign]
C:\YOUR_XML_FOLDER\gupInfo.x86.xml
C:\YOUR_XML_FOLDER\gupInfo.x64.xml
C:\YOUR_XML_FOLDER\gupInfo.arm64.xml
C:\YOUR_XML_FOLDER\gupNoUpdate.xml
